version: 2

jobs:
  dependencies:
    working_directory: /project
    docker:
      - image: node:14.16.0
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: v1-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/

  test_unit:
    working_directory: /project
    docker:
      - image: node:14.16.0
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: Tests
          command: yarn test

workflows:
  version: 2
  lint-test-deploy:
    jobs:
      - dependencies
      - test_unit:
          requires:
            - dependencies
